### ISSUE TITLE
use `rml` build error 

### ISSUE THREAD

**Issue by boiawang** [yiminghe/rml#1]
![https://gw.alicdn.com/tfs/TB1pUqfOFXXXXXZXXXXXXXXXXXX-1410-1018.png](https://gw.alicdn.com/tfs/TB1pUqfOFXXXXXZXXXXXXXXXXXX-1410-1018.png)

import {Transformer} from 'rml';

**Comment by yiminghe** [comment]
试下 https://github.com/yiminghe/rml-loader

**Comment by yiminghe** [comment]
推荐 https://github.com/yiminghe/rml-loader
